---
# IMAP Email account connection details.
email:
  username: your_username
  password: your_password
  imap_host: imap.gmail.com
  imap_port: 993

o365:
  client_id: client-app-id-here
  client_secret: client-app-secret-here

# Conditions to match for unread messages.
conditions:
  from_contains: 'person@example.com'
  subject_contains: 'Thank you for your support!'

bell:
  enable: true

sound:
  enable: false
  file: ding.mp3
